name: stock_news_flutter
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  # charts
  syncfusion_flutter_charts: ^24.1.46+1
  # dependency injection
  get_it: ^7.6.6

  # json serialization
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # state management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  # navigation
  routemaster: ^1.0.1

  # network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  http: ^1.1.2
  retrofit: ^4.0.3
  url_launcher: ^6.2.3

  # storage
  flutter_secure_storage: ^9.0.0

  # utils
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  build_runner: ^2.4.8
  retrofit_generator: '>=7.0.0 <8.0.0'
  network_image_mock: ^2.1.1


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
