name: stock_news_flutter
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  # dependency injection
  get_it: ^7.6.6
  # state management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  provider: ^6.1.1
  # navigation
  routemaster: ^1.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  build_runner: ^2.4.8


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
