// Mocks generated by Mockito 5.4.4 from annotations
// in stock_news_flutter/test/features/stock/data/repositories/stock_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stock_news_flutter/core/network/models/get_historical_stock_response_model.dart'
    as _i4;
import 'package:stock_news_flutter/core/network/service/connectivity_service.dart'
    as _i5;
import 'package:stock_news_flutter/features/stock/data/datasources/stock_remote_datasource.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StockRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStockRemoteDataSource extends _i1.Mock
    implements _i2.StockRemoteDataSource {
  MockStockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.HistoricalDataModel>> getHistoricalStock(
    String? symbol,
    DateTime? from,
    DateTime? to,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoricalStock,
          [
            symbol,
            from,
            to,
          ],
        ),
        returnValue: _i3.Future<List<_i4.HistoricalDataModel>>.value(
            <_i4.HistoricalDataModel>[]),
      ) as _i3.Future<List<_i4.HistoricalDataModel>>);
}

/// A class which mocks [ConnectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectionService extends _i1.Mock implements _i5.ConnectionService {
  MockConnectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
